from autoPyTorch.core.autonet_classes.autonet_feature_classification import AutoNetClassification
from autoPyTorch.core.autonet_classes.autonet_feature_regression import AutoNetRegression
from autoPyTorch.core.autonet_classes.autonet_feature_multilabel import AutoNetMultilabel
from autoPyTorch.core.autonet_classes.autonet_image_classification import AutoNetImageClassification
from autoPyTorch.core.autonet_classes.autonet_image_classification_multiple_datasets import AutoNetImageClassificationMultipleDatasets
