---
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '[%(levelname)s] [%(asctime)s:%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: autoPyTorch.log

  distributed_logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: distributed.log

root:
  level: DEBUG
  handlers: [console, file_handler]

loggers:

  autoPyTorch.automl_common.common.utils.backend:
    level: DEBUG
    handlers: [file_handler]
    propagate: false

  smac.intensification.intensification.Intensifier:
    level: INFO
    handlers: [file_handler, console]

  smac.optimizer.local_search.LocalSearch:
    level: INFO
    handlers: [file_handler, console]

  smac.optimizer.smbo.SMBO:
    level: INFO
    handlers: [file_handler, console]

  EnsembleBuilder:
    level: DEBUG
    handlers: [file_handler, console]

  distributed:
    level: DEBUG
    handlers: [distributed_logfile]
