name: dist-check

on:
  # Manually triggerable in github
  workflow_dispatch:

  # When a push occurs on either of these branches
  push:
    branches:
      - master
      - development

  # When a push occurs on a PR that targets these branches
  pull_request:
    branches:
      - master
      - development

  schedule:
    # Every day at 7AM UTC
    - cron: '0 07 * * *'

jobs:

  dist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build dist
      run: |
        python setup.py sdist

    - name: Twine check
      run: |
        pip install twine
        last_dist=$(ls -t dist/autoPyTorch-*.tar.gz | head -n 1)
        twine_output=`twine check "$last_dist"`
        if [[ "$twine_output" != "Checking $last_dist: PASSED" ]]; then echo $twine_output && exit 1;fi

    - name: Install dist
      run: |
        last_dist=$(ls -t dist/autoPyTorch-*.tar.gz | head -n 1)
        pip install $last_dist

    - name: PEP 561 Compliance
      run: |
        pip install mypy
        cd ..  # required to use the installed version of autosklearn
        if ! python -c "import autoPyTorch"; then exit 1; fi
