name: Tests

on:
  schedule:
    # Every Truesday at 7AM UTC
    # TODO teporary set to every day just for the PR
    #- cron: '0 07 * * 2'
    - cron: '0 07 * * *'

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast:  false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: development
        submodules: recursive
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[forecasting,test]

    - name: Run tests
      run: |
        python -m pytest --durations=200 cicd/test_preselected_configs.py -vs
