name: pre-commit

on:
  # Allow to manually trigger through github API
  workflow_dispatch:

  # Triggers with push to these branches
  push:
    branches:
      - master
      - development

  # Triggers with push to a pr aimed at these branches
  pull_request:
    branches:
      - master
      - development

jobs:

  run-all-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Init Submodules
      run: |
        git submodule update --init --recursive

    # flake8 does not restrict the version for importlib_metadata, however, it is incompatible.
    # See https://github.com/python/importlib_metadata/issues/406
    - name: Install pre-commit
      run: |
        pip install "importlib_metadata<5.0.0"
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: |
        pre-commit run --all-files
